### ISSUE TITLE
Mango install when already installed fails

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#117]
I need to update dependencies, but...

```
$ mango install
Installing NPM packages
fs.js:916
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir '/media/vojta/Linux-HDD/public_html/public_html/mango/website/node_modules'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:916:18)
    at Mango.install (/media/vojta/Linux-HDD/public_html/public_html/mango-cli/lib/mango.js:95:6)
    at doInstall (/media/vojta/Linux-HDD/public_html/public_html/mango-cli/bin/mango:81:11)
    at Command.install (/media/vojta/Linux-HDD/public_html/public_html/mango-cli/bin/mango:96:4)
    at Command.listener (/media/vojta/Linux-HDD/public_html/public_html/mango-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/media/vojta/Linux-HDD/public_html/public_html/mango-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/media/vojta/Linux-HDD/public_html/public_html/mango-cli/node_modules/commander/index.js:458:21)
```

Temporary solution: `rm -rf node_modules`

**Comment by Cactucs** [comment]
@enzy  ?
Why wontfix?

**Comment by Cactucs** [comment]
Can not reproduce
