### ISSUE TITLE
mango install fails on Cannot read property 'getExtension' of undefined

### ISSUE THREAD

**Issue by enzy** [manGoweb/mango-cli#142]
```
C:\Users\Enzy\Work\manGoweb\Rekola-web>mango install bootstrap@4.0.0-alpha.6
Installing NPM packages
C:\Users\Enzy\Work\manGoweb\Rekola-web
`-- bootstrap@4.0.0-alpha.6


C:\Users\Enzy\Work\manGoweb\mango-cli\lib\helpers\config.js:122
        var config_path = path.resolve(this.dir, CONFIG_FILENAME + '.' + this.parser.getExtension())
                                                                                    ^

TypeError: Cannot read property 'getExtension' of undefined
    at module.exports.Config.save (C:\Users\Enzy\Work\manGoweb\mango-cli\lib\helpers\config.js:122:78)
    at C:\Users\Enzy\Work\manGoweb\mango-cli\bin\mango:74:13
    at C:\Users\Enzy\Work\manGoweb\mango-cli\lib\mango.js:106:36
    at puts (C:\Users\Enzy\Work\manGoweb\mango-cli\lib\helpers\runcmd.js:15:16)
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
```

**Comment by Cactucs** [comment]
Nemám rád save metodu :D. Dvakrát jsem měnil něco v práci s configy a dvakrát jsem na to zapoměl...
