### ISSUE TITLE
Crash when running patternlab 

### ISSUE THREAD

**Issue by enzy** [manGoweb/mango-cli#38]
Introduced by watching html files and running template task, which in this case doesn't exist.

```
λ mango dev
Starting development mode
~ cleaning dist folder
~ styles
~ scripts
~ patternlab
~ patternlab finished after 2322.1 ms
~ static
~ styles finished after 8649.2 ms
~ scripts finished after 7268.1 ms
~ static finished after 4561.6 ms
~ compile finished after 0 ms
Watching sources for change and recompilation...
~ watch:sources finished after 95.8 ms
Starting BrowserSync server...
~ watch:reload finished after 1295.2 ms
WATCH: patternlab
~ watch:patternlab finished after 0.9 ms
/>
Server started, kill it with CTRL+C when you're done

C:\Work\mango-cli\node_modules\gulp\node_modules\orchestrator\index.js:153
                        throw err;
                              ^
Error: task "templates" is not defined
  at Gulp.sequence (C:\Work\mango-cli\node_modules\gulp\node_modules\orchestrator\node_modules\sequencify\index.js:14:9)
  at Gulp.Orchestrator.start (C:\Work\mango-cli\node_modules\gulp\node_modules\orchestrator\index.js:115:9)
  at changeHandler (C:\Work\mango-cli\lib\tasks\watch_sources.js:33:18)
  at EventEmitter.<anonymous> (C:\Work\mango-cli\lib\mango.js:210:4)
  at EventEmitter.emit (events.js:117:20)
  at EventEmitter.FSWatcher._emit (C:\Work\mango-cli\node_modules\chokidar\lib\index.js:115:36)
  at EventEmitter.<anonymous> (C:\Work\mango-cli\node_modules\chokidar\lib\nodefs-handler.js:209:16)
  at Object.oncomplete (fs.js:107:15)
```

// cc @ViliamKopecky

**Comment by enzy** [comment]
Fixed by e5d13b71
