### ISSUE TITLE
Static build fail

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#79]
Error when building with static assets (maybe).

// Should be added to tests

```
~/p/m/secret (master) > mango b
Building project assets for production
~ cleaning dist folder
~ styles
~ scripts
~ templates
~ images
~ static

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
  at new JS_Parse_Error (<anonymous>:1526:18)
  at js_error (<anonymous>:1534:11)
  at croak (<anonymous>:2025:9)
  at token_error (<anonymous>:2033:9)
  at unexpected (<anonymous>:2039:9)
  at semicolon (<anonymous>:2059:43)
  at simple_statement (<anonymous>:2239:73)
  at eval (<anonymous>:2112:19)
  at eval (<anonymous>:2072:24)
  at block_ (<anonymous>:2352:20)
  at eval (<anonymous>:2325:25)
  at function_ (<anonymous>:2330:15)
  at eval (<anonymous>:2160:24)
  at eval (<anonymous>:2072:24)
  at block_ (<anonymous>:2352:20)
  at eval (<anonymous>:2325:25)
  at function_ (<anonymous>:2330:15)
  at expr_atom (<anonymous>:2538:24)
  at maybe_unary (<anonymous>:2708:19)
  at expr_ops (<anonymous>:2743:24)
  at maybe_conditional (<anonymous>:2748:20)
  at maybe_assign (<anonymous>:2772:20)
  at expression (<anonymous>:2791:20)
  at eval (<anonymous>:2607:25)
  at eval (<anonymous>:2072:24)
  at expr_atom (<anonymous>:2532:35)
  at maybe_unary (<anonymous>:2708:19)
  at expr_ops (<anonymous>:2743:24)
  at maybe_conditional (<anonymous>:2748:20)
  at maybe_assign (<anonymous>:2772:20)
  at expression (<anonymous>:2791:20)
  at eval (<anonymous>:2607:25)
  at eval (<anonymous>:2072:24)
  at expr_atom (<anonymous>:2532:35)
  at maybe_unary (<anonymous>:2708:19)
  at expr_ops (<anonymous>:2743:24)
  at maybe_conditional (<anonymous>:2748:20)
  at maybe_assign (<anonymous>:2772:20)
  at expression (<anonymous>:2791:20)
  at eval (<anonymous>:2607:25)
  at eval (<anonymous>:2072:24)
  at expr_atom (<anonymous>:2532:35)
  at maybe_unary (<anonymous>:2708:19)
  at expr_ops (<anonymous>:2743:24)
  at maybe_conditional (<anonymous>:2748:20)
  at maybe_assign (<anonymous>:2772:20)
  at expression (<anonymous>:2791:20)
  at eval (<anonymous>:2607:25)
  at eval (<anonymous>:2072:24)
  at expr_atom (<anonymous>:2532:35)
  at maybe_unary (<anonymous>:2708:19)
  at expr_ops (<anonymous>:2743:24)
  at maybe_conditional (<anonymous>:2748:20)
  at maybe_assign (<anonymous>:2772:20)
  at expression (<anonymous>:2791:20)
  at expr_list (<anonymous>:2557:24)
  at subscripts (<anonymous>:2691:30)
  at expr_atom (<anonymous>:2528:24)
  at maybe_unary (<anonymous>:2708:19)
  at expr_ops (<anonymous>:2743:24)
  at maybe_conditional (<anonymous>:2748:20)
  at maybe_assign (<anonymous>:2772:20)
  at expression (<anonymous>:2791:20)
  at simple_statement (<anonymous>:2239:55)
  at eval (<anonymous>:2124:24)
  at eval (<anonymous>:2072:24)
  at eval (<anonymous>:2819:23)
  at Object.parse (<anonymous>:2829:7)
  at /home/vojta/public_html/mango-cli/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:61:33
  at Array.forEach (native)
  at Object.exports.minify (/home/vojta/public_html/mango-cli/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:56:15)
  at /home/vojta/public_html/mango-cli/node_modules/gulp-uglify/minifier.js:65:22
  at trycatch (/home/vojta/public_html/mango-cli/node_modules/gulp-uglify/minifier.js:15:12)
  at DestroyableTransform.minify [as _transform] (/home/vojta/public_html/mango-cli/node_modules/gulp-uglify/minifier.js:64:19)
  at DestroyableTransform.Transform._read (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:172:10)
  at DestroyableTransform.Transform._write (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:160:12)
  at doWrite (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_writable.js:335:12)
  at writeOrBuffer (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_writable.js:321:5)
  at DestroyableTransform.Writable.write (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_writable.js:248:11)
  at write (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at Transform.pipeOnReadable (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:67:13)
  at Transform.emit (events.js:166:7)
  at emitReadable_ (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at Transform.Readable.push (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at Transform.push (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at Transform._transform (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/index.js:43:10)
  at Transform._read (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at Transform._write (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at Transform.Writable.write (/home/vojta/public_html/mango-cli/node_modules/gulp-cached/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at Transform.ondata (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_readable.js:583:20)
  at emitOne (events.js:77:13)
  at Transform.emit (events.js:169:7)
  at readableAddChunk (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_readable.js:201:16)
  at Transform.Readable.push (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_readable.js:165:10)
  at Transform.push (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:133:32)
  at afterTransform (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:81:12)
  at TransformState.afterTransform (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:59:12)
  at doReplace (/home/vojta/public_html/mango-cli/node_modules/gulp-replace/index.js:52:18)
  at Transform.transform [as _transform] (/home/vojta/public_html/mango-cli/node_modules/gulp-replace/index.js:74:7)
  at Transform._read (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:172:10)
  at Transform._write (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:160:12)
  at doWrite (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_writable.js:335:12)
  at writeOrBuffer (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_writable.js:321:5)
  at Transform.Writable.write (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_writable.js:248:11)
  at Transform.ondata (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_readable.js:583:20)
  at emitOne (events.js:77:13)
  at Transform.emit (events.js:169:7)
  at readableAddChunk (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_readable.js:201:16)
  at Transform.Readable.push (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_readable.js:165:10)
  at Transform.push (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:133:32)
  at afterTransform (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:81:12)
  at TransformState.afterTransform (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:59:12)
  at doReplace (/home/vojta/public_html/mango-cli/node_modules/gulp-replace/index.js:52:18)
  at Transform.transform [as _transform] (/home/vojta/public_html/mango-cli/node_modules/gulp-replace/index.js:74:7)
  at Transform._read (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:172:10)
  at Transform._write (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_transform.js:160:12)
  at doWrite (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_writable.js:335:12)
  at writeOrBuffer (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_writable.js:321:5)
  at Transform.Writable.write (/home/vojta/public_html/mango-cli/node_modules/readable-stream/lib/_stream_writable.js:248:11)
  at write (/home/vojta/public_html/mango-cli/node_modules/gulp-webmake/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/vojta/public_html/mango-cli/node_modules/gulp-webmake/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/home/vojta/public_html/mango-cli/node_modules/gulp-webmake/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:67:13)
  at DestroyableTransform.emit (events.js:166:7)
  at emitReadable_ (/home/vojta/public_html/mango-cli/node_modules/gulp-webmake/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/vojta/public_html/mango-cli/node_modules/gulp-webmake/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/vojta/public_html/mango-cli/node_modules/gulp-webmake/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/home/vojta/public_html/mango-cli/node_modules/gulp-webmake/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/home/vojta/public_html/mango-cli/node_modules/gulp-webmake/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at /home/vojta/public_html/mango-cli/node_modules/gulp-webmake/index.js:31:14
  at Function.<anonymous> (/home/vojta/public_html/mango-cli/node_modules/deferred/ext/promise/cb.js:42:7)
  at Object.Deferred._settle (/home/vojta/public_html/mango-cli/node_modules/deferred/deferred.js:80:26)
  at Object.Deferred.resolve (/home/vojta/public_html/mango-cli/node_modules/deferred/deferred.js:123:15)
  at Function.exports._onresolve.then (/home/vojta/public_html/mango-cli/node_modules/deferred/_ext.js:64:4)
  at Object.Deferred._settle (/home/vojta/public_html/mango-cli/node_modules/deferred/deferred.js:80:26)
  at Object.Deferred.resolve (/home/vojta/public_html/mango-cli/node_modules/deferred/deferred.js:123:15)
  at resolve (/home/vojta/public_html/mango-cli/node_modules/fs2/read-file.js:27:7)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by Cactucs** [comment]
```
c34bde8422c448116280251f96b6caefff3027c1 is the first bad commit
commit c34bde8422c448116280251f96b6caefff3027c1
Author: Vojta Staněk <stanekv01@gmail.com>
Date:   Sat Jan 2 11:56:06 2016 +0100

    Update babel

:100644 100644 17928cc1bf2f966146e5168111dda890a5e6442a 9c32f3031d37379cd114f3444f9c9c6bc433b1c6 M	package.json

**Comment by Cactucs** [comment]
It has to do something with uglify

**Comment by enzy** [comment]
Can you put a test for this? :)
