### ISSUE TITLE
Cannot build with mango-core (works with mango)

### ISSUE THREAD

**Issue by Mikulas** [manGoweb/mango-cli#89]
```
$ mango-core build
Building project assets for production
~ cleaning dist folder
~ styles
~ scripts
~ images
~ static
[16:01:52] gulp-postcss: styles/screen.css
autoprefixer: /tmp/censored-master/theme/styles/screen.css:256:3: You should write display: flex by final spec instead of display: box
autoprefixer: /tmp/censored-master/theme/styles/screen.css:373:3: You should write display: flex by final spec instead of display: box
autoprefixer: /tmp/censored-master/theme/styles/screen.css:551:5: You should write display: flex by final spec instead of display: box
autoprefixer: /tmp/censored-master/theme/styles/screen.css:611:5: You should write display: flex by final spec instead of display: box
autoprefixer: /tmp/censored-master/theme/styles/screen.css:829:3: You should write display: flex by final spec instead of display: box
autoprefixer: /tmp/censored-master/theme/styles/screen.css:972:5: You should write display: flex by final spec instead of display: box
autoprefixer: /tmp/censored-master/theme/styles/screen.css:1335:3: You should write display: flex by final spec instead of display: box
autoprefixer: /tmp/censored-master/theme/styles/screen.css:1363:3: You should write display: flex by final spec instead of display: box
autoprefixer: /tmp/censored-master/theme/styles/screen.css:1563:3: You should write display: flex by final spec instead of display: box
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
  at exports._errnoException (util.js:856:11)
  at WriteWrap.afterWrite (net.js:767:14)
```

**Comment by Mikulas** [comment]
problem with `pngquant-bin`, solved by rebuilding pngquant from source
